/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Data.ComposicionData;
import Entidades.Composicion;
import Entidades.Equipo;
import java.time.LocalDate;
import Data.EquipoData;
import Data.MiembroData;
import Entidades.Miembro;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class ComposicionForm extends javax.swing.JInternalFrame {
    public static ComposicionData CD = new ComposicionData(); 
    public static EquipoData ED = new EquipoData(); 
    public static MiembroData MD = new MiembroData(); 
    public ComposicionForm() {
        initComponents();
        listadoEquipo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JFechaIncorporacion = new com.toedter.calendar.JDateChooser();
        JConfirmar = new javax.swing.JButton();
        JSalir = new javax.swing.JButton();
        JListadoEquipos = new javax.swing.JComboBox<>();
        JListadoMiembros = new javax.swing.JComboBox<>();

        jDesktopPane1.setBackground(new java.awt.Color(7, 146, 83));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LLENE EL FORMULARIO");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FECHA DE INCORPORACION   --->");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ELEGIR EQUIPO   --->");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ELEGIR MIEMBRO   --->");

        JConfirmar.setBackground(new java.awt.Color(100, 155, 44));
        JConfirmar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JConfirmar.setText("CONFIRMAR");
        JConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JConfirmarActionPerformed(evt);
            }
        });

        JSalir.setBackground(new java.awt.Color(100, 155, 44));
        JSalir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JSalir.setText("SALIR");
        JSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSalirActionPerformed(evt);
            }
        });

        JListadoEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JListadoEquiposMouseClicked(evt);
            }
        });
        JListadoEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JListadoEquiposActionPerformed(evt);
            }
        });

        JListadoMiembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JListadoMiembrosActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JFechaIncorporacion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JConfirmar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JListadoEquipos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JListadoMiembros, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(JConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JListadoMiembros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30)
                        .addComponent(JFechaIncorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(34, 34, 34)
                        .addComponent(JListadoEquipos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JFechaIncorporacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JListadoEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JListadoMiembros, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JConfirmarActionPerformed
          int n = 1;
          SimpleDateFormat formatoFecha = new SimpleDateFormat("dd-MM-yyyy");
          String fecha = formatoFecha.format(JFechaIncorporacion.getDate());
          LocalDate f_incorporacion = LocalDate.parse(fecha, DateTimeFormatter.ofPattern("dd-MM-yyyy"));

          Equipo e = (Equipo)JListadoEquipos.getSelectedItem();
          Miembro m = (Miembro)JListadoMiembros.getSelectedItem();
             
          for(Composicion com : CD.listarMiembrosEquipo()){
               int IdE = com.getIdEquipo();
               int IdM = com.getIdMiembro();
               if(IdE == e.getIdEquipo() && IdM == m.getIdMiembro()){
                   n = 0;
                   break;
               } else if (IdM == m.getIdMiembro() && IdE != e.getIdEquipo()){
                   n = -1;
                   break;
               }
          }
              
          if(n == 0){
              JOptionPane.showMessageDialog(this, "EL MIEMBRO YA ESTÁ EN EL EQUIPO " + e.getIdEquipo());
          } else if (n == -1){                     
              Composicion c = new Composicion(f_incorporacion,  e.getIdEquipo(), m.getIdMiembro());
              CD.actualizarMiembroEquipo(c);
          } else {
              Composicion c = new Composicion(f_incorporacion,  e.getIdEquipo(), m.getIdMiembro());
              CD.insertarMiembro(c);
              listadoMiembros();
          }
    }//GEN-LAST:event_JConfirmarActionPerformed

    private void JSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSalirActionPerformed
        dispose();
    }//GEN-LAST:event_JSalirActionPerformed

    private void JListadoEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JListadoEquiposActionPerformed
        listadoMiembros();
    }//GEN-LAST:event_JListadoEquiposActionPerformed

    private void JListadoMiembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JListadoMiembrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JListadoMiembrosActionPerformed

    private void JListadoEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JListadoEquiposMouseClicked
        
    }//GEN-LAST:event_JListadoEquiposMouseClicked

    private void listadoEquipo(){
        for(Equipo e :  ED.listaEquipo()){
             JListadoEquipos.addItem(e);
        }
    }
    
    private void listadoMiembros(){
        JListadoMiembros.removeAllItems();
        for(Miembro m :  MD.listarMiembrosSinEquipo()){
             if(MD.listarMiembrosSinEquipo().isEmpty()){
                JOptionPane.showMessageDialog(this, "TODOS LOS MIEMBROS ASIGNADOS");
             } else {
             JListadoMiembros.addItem(m);
             }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JConfirmar;
    private com.toedter.calendar.JDateChooser JFechaIncorporacion;
    private javax.swing.JComboBox<Equipo> JListadoEquipos;
    private javax.swing.JComboBox<Miembro> JListadoMiembros;
    private javax.swing.JButton JSalir;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    
}
